### ISSUE TITLE
Wrong layout

### ISSUE THREAD

**Issue by e00E** [rust-lang-nursery/rust-bindgen#1041] opened 2017-09-26 06:33 UTC
### Input C/C++ Header

```C++
#pragma pack(push)
#pragma pack(1)
struct S5 {
   signed f0 : 11;
   unsigned f1 : 12;
   unsigned f2 : 23;
};
#pragma pack(pop)
```

### Bindgen Invocation

```
$ bindgen failing.h -o failing.rs
```

### Actual Results

While running bindgen we get:
```
ERROR:bindgen::codegen::struct_layout: Calculated wrong layout for S5, too more 2 bytes
```
 but the output is created nonetheless:
```rust
[repr(C)]
#[derive(Debug, Copy)]
pub struct S5 {
    pub _bitfield_1: [u32; 2usize],
    pub __bindgen_align: [u8; 0usize],
}
```

Then when running the tests:
```
---- bindgen_test_layout_S5 stdout ----
        thread 'bindgen_test_layout_S5' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `6`: Size of: S5', failing.rs:11:4
```

**Comment by emilio** [comment] 2017-09-26 10:50
Dupe of https://github.com/rust-lang-nursery/rust-bindgen/issues/537. Thanks for the report!

**Closed by emilio** 2017-09-26 10:50 UTC
