### ISSUE TITLE
cups-sys bindgen layout tests fail on Linux

### ISSUE THREAD

**Issue by LegNeato** [rust-lang-nursery/rust-bindgen#1011] opened 2017-09-21 20:22 UTC
[`cups-sys`](https://github.com/LegNeato/cups-sys/blob/master/build.rs#L25) currently needs to turn off layout tests as they fail on Linux for `bindgen_test_layout_max_align_t`.

You can repro by installing `libcups2-dev` on ubuntu, removing [this line](https://github.com/LegNeato/cups-sys/blob/master/build.rs#L25), and building `cups-sys`.

**Comment by fitzgen** [comment] 2017-09-21 20:29
Thanks for the bug report! This is a duplicate of https://github.com/rust-lang-nursery/rust-bindgen/issues/550

**Closed** 2017-09-21 20:29 UTC
