### ISSUE TITLE
--use-core bindings refers std

### ISSUE THREAD

**Issue by pepyakin** [rust-lang-nursery/rust-bindgen#1015] opened 2017-09-22 09:34 UTC
### Input C/C++ Header

```C++
// bindgen-flags: --impl-debug --use-core --raw-line "extern crate core;"

class C {
    bool a: 1;
    bool b: 7;
    int large_array[50];
};
```

### Bindgen Invocation

See bindgen-flags above

### Actual Results

```rust
// ... stripped

extern crate core;

#[repr(C)]
#[derive(Copy)]
pub struct C {
    pub _bitfield_1: u8,
    pub large_array: [::std::os::raw::c_int; 50usize]
}

// stripped ...
```

### Expected Results

Despite that `--use-core` flag is provided `large_array` field having a type which refers `std`.
I expect that either error is printed stating that bindings couldn't be generated with `--use-core` or bindings which don't use std generated.

**Comment by fitzgen** [comment] 2017-09-22 18:30
Nice catch!

I expect the fix for this is really easy (just forgetting to look at the prefix and emitting `std` regardless somewhere in `src/codegen/mod.rs`), but I hesitate marking it `E-easy` without being able to add clear instructions on how to fix this. Needs a little bit of investigation, so marking it `E-less-easy`.

**Comment by emilio** [comment] 2017-09-24 22:30
This is working as expected, `--use-core` doesn't replace `std`, since it doesn't include them. You need to manually point to somewhere, e.g., libc, using `--ctypes-prefix`.

Worth pointing it out in the FAQ or something though, I guess.

**Comment by joshlf** [comment] 2018-07-29 04:58
To clarify: The issue is that some types are present in `std` and not in `core`, and thus `--use-core` has to still rely on `std` for those types? Would it be feasible to add the offending types to `core` to fix this problem?

**Comment by emilio** [comment] 2018-07-29 17:16
Either that, or using the `--ctypes-prefix` option, which is meant just for that. I'm not sure the `c_*` types are meant to be in `core`.

**Comment by emilio** [comment] 2018-07-29 17:17
Closing per https://github.com/rust-lang-nursery/rust-bindgen/issues/1015#issuecomment-331744782, since as things stand `ctypes-prefix` should be used. If rust puts the ctypes in `core`, then another issue can be opened to make bindgen adapt to that.

**Closed by emilio** 2018-07-29 17:17 UTC
Labels: E-less-easy, I-bogus-codegen, bug, help wanted

**Comment by joshlf** [comment] 2018-07-29 17:55
If these types aren't in `core`, what would we pass to `ctypes-prefix`?

**Comment by emilio** [comment] 2018-07-30 00:12
You should pass, e.g., `libc`, to use the `libc` crate, or a module / crate of your own that defines the needed types for the target architecture.

Though usually you'd want `libc`, I suspect.

**Comment by AllenChong** [comment] 2018-08-09 15:44
issue

**Comment by coffeenotfound** [comment] 2020-12-28 07:01
The description of `--use-core` is "Use types from Rust core instead of std."
If it doesn't do that how in gods name is it "working as intended". What _does_ it do?

**Comment by emilio** [comment] 2020-12-28 12:04
Well, there is not (or didn't use to be at least) any alternative for `std::os::raw::c_*` types in core, so it's not clear to me what output do you expect?

We provide an option to not use std types for those and use a crate or module of your choice. Maybe the description should include "when possible" or something.
