### ISSUE TITLE
handling the same names of unnamed enum member and define

### ISSUE THREAD

**Issue by Dushistov** [rust-lang-nursery/rust-bindgen#1242] opened 2018-01-30 13:32 UTC
### Input C/C++ Header

This is reduced test case. I created it based on headers of `glibc 2.26`.
You can see in comments from which standard headers I got `C` code.
```C++
//netinet/in.h
enum
  {
IPPORT_RESERVED = 1024,
};
//netdb.h
# define IPPORT_RESERVED        1024
```

### Bindgen Invocation

```
$ ~/bin/bindgen.sh --no-layout-tests --no-rustfmt-bindings test.h  | ~/bin/rustfmt-nightly.sh
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

pub const IPPORT_RESERVED: ::std::os::raw::c_uint = 1024;
pub const IPPORT_RESERVED: _bindgen_ty_1 = 1024;
pub type _bindgen_ty_1 = u32;

```
as result compile time error from `rustc`:
```
the name `IPPORT_RESERVED` is defined multiple times
```

### Expected Results

I'm creating bindging for 3rdparty library, and it's headers indirectly include both headers (**netdb.h** and **netinet/in.h**).
It would be nice to add some kind of mechanizm to prevent such kind of errors
without need to edit glibc headers or 3rdparty library's headers.

**Comment by fitzgen** [comment] 2018-01-30 20:52
Thanks for filing an issue!

**Comment by emilio** [comment] 2018-01-30 22:52
Closing as a dupe of #687.

**Closed by emilio** 2018-01-30 22:52 UTC
Labels: A-enums, A-macros, I-bogus-codegen

**Comment by trsh** [comment] 2018-05-10 06:03
What is the solution. Also getting > `IPPORT_RESERVED` must be defined only once in the value namespace of this module
