### ISSUE TITLE
bindgen  0.42.1 f fails on win32 with latest release of clang

### ISSUE THREAD

**Issue by demoray** [rust-lang-nursery/rust-bindgen#1416] opened 2018-10-08 20:07 UTC
bindgen 0.42.1 fails to find libclang.dll on Windows 1064bit. 

* clang v7.0.0, installed in default location (C:\Program Files\LLVM\bin).
* cargo 1.29.0
* rustc 1.21.1

backdating to bindgen 0.41.0 finds libclang.dll as expected.

```
$ bindgen -h
```

### Actual Results

```
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found( invalid: [])"', libcore\result.rs:945:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: BaseThreadInitThunk
  18: RtlUserThreadStart
```

### Expected Results

Normal 'bindgen -h' output.

**Comment by emilio** [comment] 2018-10-09 08:53
What about 0.42.0? This looks like a regression by the recent clang-sys changes. cc @KyleMayes

**Comment by demoray** [comment] 2018-10-09 13:27
0.42.0 fails with the same error.

**Comment by emilio** [comment] 2018-10-10 00:10
What is the full path of the dll that is not found?

**Comment by demoray** [comment] 2018-10-10 12:10
I can confirm that @KyleMayes 's update of clang-sys to 0.26.1 addresses this issue.

**Comment by emilio** [comment] 2018-10-10 12:46
Alright, closing as not a bindgen bug. Thanks much for the quick turnaround again @KyleMayes!

**Closed by emilio** 2018-10-10 12:46 UTC
