### ISSUE TITLE
Possibility to make bindgen only generate a single `extern` block?

### ISSUE THREAD

**Issue by faern** [rust-lang-nursery/rust-bindgen#1261] opened 2018-02-22 23:58 UTC
### Input C/C++ Header

```C
void foo();
void bar();
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
extern "C" {
    pub fn foo();
}
extern "C" {
    pub fn bar();
}
```

### Expected Results

It becomes very verbose for no reason that is apparent to me. Personally I would prefer the following output:
```rust
extern "C" {
    pub fn foo();
    pub fn bar();
}
```

Maybe there is already a way to do this, but I could not find it. Nor did I find any issue touching the issue.

**Comment by emilio** [comment] 2018-02-23 00:12
Closing as a dupe of https://github.com/rust-lang-nursery/rust-bindgen/issues/564.

TL;DR: Patches welcome as long as they're not a burden to maintain, but... I can't think of a nice way to do this that doesn't include adding yet another intermediate representation, or processing phase.

**Closed by emilio** 2018-02-23 00:12 UTC
