### ISSUE TITLE
Add `bindgen::Builder::derive_copy` to control whether we emit `derive(Copy)` on type definitions

### ISSUE THREAD

**Issue by ctaggart** [rust-lang-nursery/rust-bindgen#948] opened 2017-09-04 17:24 UTC
I'm getting a lot of errors like `the trait Copy may not be implemented for this type`, so I went to disable it like I did for `.derive_debug`, but there isn't an option to turn it off. Shouldn't there be?
``` rust
    let mut builder = bindgen::Builder::default()
        .header("src/octhc.h")
        // .... snip ...
        .derive_debug(false)
        // .derive_copy(false)
        .whitelist_recursively(false)
        .layout_tests(false)
        .generate_comments(false);
```

**Comment by emilio** [comment] 2017-09-04 20:22
Probably, yeah... Ideally shouldn't be needed. This is basically a dupe of #944.

Right now the analysis landed in #866 assumed that everything not whitelisted should assume to derive copy, when it should be the other way around.

**Comment by fitzgen** [comment] 2017-09-05 16:10
It should be pretty straightforward to add a `fn derive_copy(mut self, doit: bool) -> Self` method to `Builder`. One could look at how its done for `derive_debug` to see how to thread the pieces together.

Happy to mentor anyone who wants to take this.

**Comment by fitzgen** [comment] 2017-09-05 16:12
> Probably, yeah... Ideally shouldn't be needed. This is basically a dupe of #944.
> 
> Right now the analysis landed in #866 assumed that everything not whitelisted should assume to derive copy, when it should be the other way around.

That is certainly a bug, but it also makes sense to allow people to avoid deriving `Copy` in general. In other words, this isn't a dupe in my opinion.

**Comment by mchlrhw** [comment] 2017-09-06 15:39
@fitzgen I'd be happy to help out with this. Just getting into Rust and looking for ways to contribute in my spare time. I've implemented this in my fork, should I just open a PR?

**Comment by mchlrhw** [comment] 2017-09-06 15:45
@highfive: assign me

**Closed** 2017-09-06 20:12 UTC
Labels: A-derive, C-assigned, E-easy, enhancement, help wanted
