### ISSUE TITLE
Bindgen generates syntactically invalid Rust code

### ISSUE THREAD

**Issue by jjpe** [rust-lang-nursery/rust-bindgen#1174] opened 2017-12-03 10:03 UTC
I just tried to update my `emacs_module_bindings` crate to use `bindgen 0.31` rather than `bindgen 0.29`.   After updating the `Cargo.toml` entry for `bindgen`  and running `cargo update` I encountered an unexpected form of breakage when trying to `cargo build`:

### Input C/C++ Header

NOTE: Tried to perform the steps originally outlined in this section, by changing my build script to
call `bindgen::Builder::dump_preprocessed_input` (see further down).   While the build script 
itself seems perfectly fine, the build still fails for the same reason without dumping any 
output.  So I've just stripped out most of the preprocessor code myself, but 
the difference is less than 10 SLOC as it was just a check for C++, which the 
snippet below assumes to be false.

```C++
#ifndef EMACS_MODULE_H
#define EMACS_MODULE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

# define EMACS_NOEXCEPT

/* Current environment.  */
typedef struct emacs_env_25 emacs_env;

/* Opaque pointer representing an Emacs Lisp value.
   BEWARE: Do not assume NULL is a valid value!  */
typedef struct emacs_value_tag *emacs_value;

enum { emacs_variadic_function = -2 };

/* Struct passed to a module init function (emacs_module_init).  */
struct emacs_runtime
{
  /* Structure size (for version checking).  */
  ptrdiff_t size;

  /* Private data; users should not touch this.  */
  struct emacs_runtime_private *private_members;

  /* Return an environment pointer.  */
  emacs_env *(*get_environment) (struct emacs_runtime *ert);
};


/* Possible Emacs function call outcomes.  */
enum emacs_funcall_exit
{
  /* Function has returned normally.  */
  emacs_funcall_exit_return = 0,

  /* Function has signaled an error using `signal'.  */
  emacs_funcall_exit_signal = 1,

  /* Function has exit using `throw'.  */
  emacs_funcall_exit_throw = 2,
};

struct emacs_env_25
{
  /* Structure size (for version checking).  */
  ptrdiff_t size;

  /* Private data; users should not touch this.  */
  struct emacs_env_private *private_members;

  /* Memory management.  */

  emacs_value (*make_global_ref) (emacs_env *env,
				  emacs_value any_reference);

  void (*free_global_ref) (emacs_env *env,
			   emacs_value global_reference);

  /* Non-local exit handling.  */

  enum emacs_funcall_exit (*non_local_exit_check) (emacs_env *env);

  void (*non_local_exit_clear) (emacs_env *env);

  enum emacs_funcall_exit (*non_local_exit_get)
    (emacs_env *env,
     emacs_value *non_local_exit_symbol_out,
     emacs_value *non_local_exit_data_out);

  void (*non_local_exit_signal) (emacs_env *env,
				 emacs_value non_local_exit_symbol,
				 emacs_value non_local_exit_data);

  void (*non_local_exit_throw) (emacs_env *env,
				emacs_value tag,
				emacs_value value);

  /* Function registration.  */

  emacs_value (*make_function) (emacs_env *env,
				ptrdiff_t min_arity,
				ptrdiff_t max_arity,
				emacs_value (*function) (emacs_env *env,
							 ptrdiff_t nargs,
							 emacs_value args[],
							 void *)
				  EMACS_NOEXCEPT,
				const char *documentation,
				void *data);

  emacs_value (*funcall) (emacs_env *env,
                          emacs_value function,
                          ptrdiff_t nargs,
                          emacs_value args[]);

  emacs_value (*intern) (emacs_env *env,
                         const char *symbol_name);

  /* Type conversion.  */

  emacs_value (*type_of) (emacs_env *env,
			  emacs_value value);

  bool (*is_not_nil) (emacs_env *env, emacs_value value);

  bool (*eq) (emacs_env *env, emacs_value a, emacs_value b);

  intmax_t (*extract_integer) (emacs_env *env, emacs_value value);

  emacs_value (*make_integer) (emacs_env *env, intmax_t value);

  double (*extract_float) (emacs_env *env, emacs_value value);

  emacs_value (*make_float) (emacs_env *env, double value);

  /* Copy the content of the Lisp string VALUE to BUFFER as an utf8
     null-terminated string.

     SIZE must point to the total size of the buffer.  If BUFFER is
     NULL or if SIZE is not big enough, write the required buffer size
     to SIZE and return false.

     Note that SIZE must include the last null byte (e.g. "abc" needs
     a buffer of size 4).

     Return true if the string was successfully copied.  */

  bool (*copy_string_contents) (emacs_env *env,
                                emacs_value value,
                                char *buffer,
                                ptrdiff_t *size_inout);

  /* Create a Lisp string from a utf8 encoded string.  */
  emacs_value (*make_string) (emacs_env *env,
			      const char *contents, ptrdiff_t length);

  /* Embedded pointer type.  */
  emacs_value (*make_user_ptr) (emacs_env *env,
				void (*fin) (void *) EMACS_NOEXCEPT,
				void *ptr);

  void *(*get_user_ptr) (emacs_env *env, emacs_value uptr);
  void (*set_user_ptr) (emacs_env *env, emacs_value uptr, void *ptr);

  void (*(*get_user_finalizer) (emacs_env *env, emacs_value uptr))
    (void *) EMACS_NOEXCEPT;
  void (*set_user_finalizer) (emacs_env *env,
			      emacs_value uptr,
			      void (*fin) (void *) EMACS_NOEXCEPT);

  /* Vector functions.  */
  emacs_value (*vec_get) (emacs_env *env, emacs_value vec, ptrdiff_t i);

  void (*vec_set) (emacs_env *env, emacs_value vec, ptrdiff_t i,
		   emacs_value val);

  ptrdiff_t (*vec_size) (emacs_env *env, emacs_value vec);
};

/* Every module should define a function as follows.  */
extern int emacs_module_init (struct emacs_runtime *ert);

#endif /* EMACS_MODULE_H */

```

### Bindgen Invocation

Regular:
```Rust
fn main() { // build.rs
    let out_dir = env::var("OUT_DIR").unwrap();
    bindgen::builder()
        .header("./include/emacs-module.h")
        .generate()
        .unwrap()
        .write_to_file(Path::new(&out_dir).join("emacs_module.rs"))
        .unwrap();

}
```
Trying to dump output:
```Rust
fn main() { // build.rs
    bindgen::builder()
        .header("./include/emacs-module.h")
        .dump_preprocessed_input()
        .expect("this message is not printed.");
}
```

### Actual Results

```
-*- mode: cargo-process; default-directory: "~/Documents/TUDelft/MSc/thesis/prototypes/emacs_module_bindings.rs/" -*-
Cargo-Process started at Sun Dec  3 10:59:33

cargo build 
   Compiling emacs_module_bindings v0.7.0 (file:///Users/j/Documents/TUDelft/MSc/thesis/prototypes/emacs_module_bindings.rs)
error: unexpected close delimiter: `]`
   --> /Users/j/Documents/TUDelft/MSc/thesis/prototypes/emacs_module_bindings.rs/target/debug/build/emacs_module_bindings-9901bf402d8519b7/out/emacs_module.rs:108:33
    |
108 | #[derive(Copy, Clone)]; 16usize ] , }#[test]
    |                                 ^

error: Could not compile `emacs_module_bindings`.

To learn more, run the command again with --verbose.

Cargo-Process exited abnormally with code 101 at Sun Dec  3 10:59:42

```

I also took a wider source snippet from the generated source code than the error provides:
```` Rust
#[repr(C)]
#[derive(Copy, Clone)]; 16usize ] , }#[test]  // <- This is the defective line
fn bindgen_test_layout___mbstate_t() {
    assert_eq!(
        ::std::mem::size_of::<__mbstate_t>(),
        128usize,
        concat!("Size of: ", stringify!(__mbstate_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__mbstate_t>(),
        8usize,
        concat!("Alignment of ", stringify!(__mbstate_t))
    );
}
````

### Expected Results

I expected one of either:
1. The generated bindings continue to work as they did in `bindgen 0.29`. This is the ideal case
2. The generated bindings are changed thus the code using it will need maintenance, but at least the build doesn't fail due to a syntactic issue in generated Rust code.

**Comment by emilio** [comment] 2017-12-03 12:08
This is a rustfmt bug, see https://github.com/rust-lang-nursery/rust-bindgen/issues/1156. Closing as a dupe of that, but thanks for the report!

Feel free to comment / reopen if it doesn't end up being it.

**Closed by emilio** 2017-12-03 12:08 UTC

**Comment by jjpe** [comment] 2017-12-03 12:43
Using the `rustfmt` nightly indeed turned out to help, thanks for the link!
