### ISSUE TITLE
failed layout test for function when class name is same

### ISSUE THREAD

**Issue by ctaggart** [rust-lang-nursery/rust-bindgen#1028] opened 2017-09-24 10:56 UTC
I'm not sure about the exact cause, but it looks like the layout tests may be failing if the class name is the same as the function name. I'm guessing. Here is the test case.

### Input C/C++ Header

```C++
class a {
  virtual int b();
  int c;
};
class octave_function : a {
  bool d;
};
```

### Bindgen Invocation

``` bash
#!/usr/bin/env bash
set -eu
export RUST_BACKTRACE=1
clang-3.9 --std=c++11 -c __bindgen.ii

~/rust-bindgen/target/release/bindgen \
    --output __bindgen.rs \
    --enable-cxx-namespaces \
    --whitelist-type octave.* \
    --whitelist-function octave.* \
    --use-core \
    --raw-line "extern crate core;" \
    --opaque-type std::.* \
    __bindgen.ii \
    -- -v -x c++ -std=c++11 \
    2>/dev/null

rustc --test __bindgen.rs
./__bindgen \
    2>&1 \
    | grep 'test root::bindgen_test_layout_octave_function ... FAILED'
```

### Actual Results

Layout tests fail.

### Expected Results

Layout tests pass.

**Comment by emilio** [comment] 2017-09-24 21:48
This is a dupe of #380, I'm pretty sure.

Thanks for the report though!

**Closed by emilio** 2017-09-24 21:48 UTC

**Comment by ctaggart** [comment] 2017-09-25 07:59
Well, you've got a new test case. I'll track that ticket.
