### ISSUE TITLE
Incorrect link_name is generated for extern "C" functions for 32 bit linux

### ISSUE THREAD

**Issue by chengchangwu** [rust-lang-nursery/rust-bindgen#904] opened 2017-08-11 11:02 UTC
Like #728, but for 32 bit Linux.

### Input C/C++ Header

```C
struct ec_sdo_request;
typedef struct ec_sdo_request ec_sdo_request_t;
int *ecrt_sdo_request_data(
        ec_sdo_request_t *req /**< SDO request. */
        );
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ec_sdo_request {
    _unused: [u8; 0],
}
pub type ec_sdo_request_t = ec_sdo_request;
extern "C" {
    #[link_name = "_Z21ecrt_sdo_request_data"]
    pub fn ecrt_sdo_request_data(req: *mut ec_sdo_request_t)
     -> *mut ::std::os::raw::c_int;
}
```
### Expected Results

```Rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ec_sdo_request {
    _unused: [u8; 0],
}
pub type ec_sdo_request_t = ec_sdo_request;
extern "C" {
    pub fn ecrt_sdo_request_data(req: *mut ec_sdo_request_t)
     -> *mut ::std::os::raw::c_int;
}
```

**Comment by emilio** [comment] 2017-08-11 11:37
Which clang version is this?

**Comment by emilio** [comment] 2017-08-11 11:39
This sounds like https://github.com/rust-lang-nursery/rust-bindgen/issues/528

**Comment by chengchangwu** [comment] 2017-08-11 13:01
I've clang-3.8, clang-3.9 and and old libclang1-3.6 installed. After removing clang-3.8 and old libclang1-3.6, the problem is fixed.

Thanks.

**Comment by emilio** [comment] 2017-08-11 13:12
Closed as a dupe of #528 then, thanks for checking!

There's a workaround explained there.

**Closed by emilio** 2017-08-11 13:12 UTC
